# Generated by .github/workflows/release.yml in xuzhaocheng/Maccy.
# Edit packaging/homebrew/cask.rb.template there, not this file.
cask "maccy-plus" do
  version "2.7.1-2"
  sha256 "32b6ea05bf81394d62f940ae0e9e8ad75d8b840478bbec5fcaf16253d9aa7400"

  url "https://github.com/xuzhaocheng/Maccy/releases/download/#{version}/Maccy-#{version}.zip"
  name "Maccy Plus"
  desc "Clipboard manager with extra productivity features"
  homepage "https://github.com/xuzhaocheng/Maccy"

  conflicts_with cask: "maccy"
  depends_on macos: :sonoma

  app "Maccy.app"

  # The build is ad-hoc signed and not notarized, so Gatekeeper would refuse
  # to open it. Remove the quarantine attribute that the download adds.
  postflight_steps do
    run "/usr/bin/xattr",
        args:           ["-dr", "com.apple.quarantine", "{{appdir}}/Maccy.app"],
        writable_paths: ["{{appdir}}/Maccy.app"]
  end

  uninstall quit: "org.p0deje.Maccy"

  zap trash: [
    "~/Library/Application Support/Maccy",
    "~/Library/Containers/org.p0deje.Maccy",
  ]
end
